import 'genotype.dart';

class Individual {
  final String name;

  final Genotype genotype;

  static int _autoGeneratedName = -4;

  Individual(String genotype, [String? name])
      : name = name ?? 'Indiv${_autoGeneratedName++}',
        genotype = Genotype(genotype);

  @override
  String toString() {
    return '$name(${genotype.bloodType})';
  }
}
